import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {ErrorBlock, Skeleton, Image} from "antd-mobile";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image
          className={styles.image}
          src={'https://adinf-robotaxi.cdn.bcebos.com/lowcode/1656560723709767992-125c58f9-f827-11ec-8d42-6c92bf2853ce.png'}
          placeholder={
            <Skeleton
              animated
              style={{
                '--height': '51vw',
                '--border-radius': '8px',
                '--width': '95%',
                margin: '0 auto',
              }}
            />
          }
          fallback={
            <ErrorBlock
              title="网络似乎不太好哦"
              description="待会再来试试吧"
            />
          }
        />
      </div>
    </>
  )
}
